// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1vY1rhSLena9fanxFTgTgg1lyiq4uD0',
    appId: '1:216447926706:web:89faf18be98f67d19c64ab',
    messagingSenderId: '216447926706',
    projectId: 'mamacare-147ec',
    authDomain: 'mamacare-147ec.firebaseapp.com',
    storageBucket: 'mamacare-147ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQBN9gBP4Sm7Opp0W_mhXDX_b43vejyo',
    appId: '1:216447926706:android:3331106c4d64e9bf9c64ab',
    messagingSenderId: '216447926706',
    projectId: 'mamacare-147ec',
    storageBucket: 'mamacare-147ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2miqCVBKjN3q5sr1T2XxRbE3AA9V_HI4',
    appId: '1:216447926706:ios:e061ca4b2acf2d249c64ab',
    messagingSenderId: '216447926706',
    projectId: 'mamacare-147ec',
    storageBucket: 'mamacare-147ec.firebasestorage.app',
    iosBundleId: 'com.example.mamaCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2miqCVBKjN3q5sr1T2XxRbE3AA9V_HI4',
    appId: '1:216447926706:ios:e061ca4b2acf2d249c64ab',
    messagingSenderId: '216447926706',
    projectId: 'mamacare-147ec',
    storageBucket: 'mamacare-147ec.firebasestorage.app',
    iosBundleId: 'com.example.mamaCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd1vY1rhSLena9fanxFTgTgg1lyiq4uD0',
    appId: '1:216447926706:web:6630029b1d341b209c64ab',
    messagingSenderId: '216447926706',
    projectId: 'mamacare-147ec',
    authDomain: 'mamacare-147ec.firebaseapp.com',
    storageBucket: 'mamacare-147ec.firebasestorage.app',
  );
}
